config/routes.rb
Rails.application.routes.draw do
  

  resources :ranches do 
    resources :tasks do
      member do 
        patch :done
        patch :undone
        patch :star
        patch :unstar
      end
    end 
  end


  resources :staffs
  devise_for :users

  post '/' => 'users#create', :as => 'user'
  
  root 'plainpage#index'

end

app/models/ranch.rb
class Ranch < ActiveRecord::Base
  belongs_to :users
  
  has_many :staffs, :through => :ranchstaffs

  has_many :tasks 


  scope :myranch, -> { where(user_id: current_user.id) }

end

app/models/ranchstaff.rb
class Ranchstaff < ActiveRecord::Base

  belongs_to :ranch
  belongs_to :staff

  
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :user

  has_many :ranchstaffs
  has_many :ranches, :through => :ranchstaffs
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :ranch
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :ranches
  has_many :staffs


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    unless current_user.ranches.count == 0
    @ranch = current_user.ranches.first
    request.env['omniauth.origin'] || ranch_path(@ranch)
    end
  end
end

app/controllers/plainpage_controller.rb
class PlainpageController < ApplicationController
  before_action :authenticate_user! 

  def index
    flash[:success ] = "Success Flash Message: Welcome to GentellelaOnRails"
    #other alternatives are
    # flash[:warn ] = "Israel don't quite like warnings"
    #flash[:danger ] = "Naomi let the dog out!"
  end
end

app/controllers/ranches_controller.rb
class RanchesController < ApplicationController
  before_action :set_ranch, only: [:show, :edit, :update, :destroy]

  # GET /ranches
  # GET /ranches.json


  def index
    @ranches = current_user.ranches
  end

  # GET /ranches/1
  # GET /ranches/1.json
  def show
    @tasks = @ranch.tasks.all
  end

  # GET /ranches/new
  def new
    @ranch = Ranch.new
  end

  # GET /ranches/1/edit
  def edit
  end

  # POST /ranches
  # POST /ranches.json
  def create
    @ranch = Ranch.new(ranch_params)
    @ranch.update(user_id: current_user.id)
    respond_to do |format|
      if @ranch.save
        format.html { redirect_to @ranch, notice: 'Ranch was successfully created.' }
        format.json { render :show, status: :created, location: @ranch }
      else
        format.html { render :new }
        format.json { render json: @ranch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ranches/1
  # PATCH/PUT /ranches/1.json
  def update
    respond_to do |format|
      if @ranch.update(ranch_params)
        format.html { redirect_to @ranch, notice: 'Ranch was successfully updated.' }
        format.json { render :show, status: :ok, location: @ranch }
      else
        format.html { render :edit }
        format.json { render json: @ranch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ranches/1
  # DELETE /ranches/1.json
  def destroy
    @ranch.destroy
    respond_to do |format|
      format.html { redirect_to ranches_url, notice: 'Ranch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranch
      @ranch = Ranch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ranch_params
      params.require(:ranch).permit(:name, :user_id)
    end
end

app/controllers/ranchstaffs_controller.rb
class RanchstaffsController < ApplicationController
  class TasksController < ApplicationController
  before_action :set_ranch
  before_action :set_task, except: [:create]

  def create 
    @task = @staff.ranchstaffs.create(ranchstaff_params)
    if @ranchstaff.save
      
      flash[:success] = "The task was created "
    else 
      flash[:success] = "The task was not created "
    end
    redirect_to @ranch
  end 

  def destroy 
    if @task.delete
      flash[:success] = "The task was deleted "
    else 
      flash[:success] = "The task was not deleted "
    end 
    redirect_to @ranch
  end 

  def done
    @task.update(done: true)
    @task.update(completed_at: Time.now)
    redirect_to @ranch
  end 

  def undone
    @task.update(done: false)
    redirect_to @ranch
  end

  def star
    @task.update(star: true)
    redirect_to @ranch
  end 

  def unstar
    @task.update(star: false)
    redirect_to @ranch
  end 

private

  def task_params
    params[:task].permit(:content, :date, :assigned_to)
  end

  def set_ranch 
    @ranch = Ranch.find(params[:ranch_id])
  end 

  def set_task 
    @task = @ranch.tasks.find(params[:id])
  end 

end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /ranches
  # GET /ranches.json
  def index
    @staffs = current_user.staffs
  end

  # GET /ranches/1
  # GET /ranches/1.json
  def show
    
  end

  # GET /ranches/new
  def new
    @staff = Staff.new
    @all_ranch = current_user.ranches
    @staff_ranch = @staff.ranchstaffs.build
  end

  # GET /ranches/1/edit
  def edit
  end

  # POST /ranches
  # POST /ranches.json
  def create
    @staff = Staff.new(staff_params)

    @staff.update(user_id: current_user.id)
    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ranches/1
  # PATCH/PUT /ranches/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ranches/1
  # DELETE /ranches/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Ranch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :user_id, :cat, :ranch_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_ranch
  before_action :set_task, except: [:create]

  def create 
    @task = @ranch.tasks.create(task_params)
    if @task.save
      @task.update(done: false)
      flash[:success] = "The task was created "
    else 
      flash[:success] = "The task was not created "
    end
    redirect_to @ranch
  end 

  def destroy 
    if @task.delete
      flash[:success] = "The task was deleted "
    else 
      flash[:success] = "The task was not deleted "
    end 
    redirect_to @ranch
  end 

  def done
    @task.update(done: true)
    @task.update(completed_at: Time.now)
    redirect_to @ranch
  end 

  def undone
    @task.update(done: false)
    redirect_to @ranch
  end

  def star
    @task.update(star: true)
    redirect_to @ranch
  end 

  def unstar
    @task.update(star: false)
    redirect_to @ranch
  end 

private

  def task_params
    params[:task].permit(:content, :date, :assigned_to)
  end

  def set_ranch 
    @ranch = Ranch.find(params[:ranch_id])
  end 

  def set_task 
    @task = @ranch.tasks.find(params[:id])
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/ranches_helper.rb
module RanchesHelper
end

app/helpers/ranchstaff_helper.rb
module RanchstaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<%- if user_signed_in? %> 
  <!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "GentelellaOnRails" %> </title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body class="nav-md">
<div class="container body">
  <% flash.each do |key, value| %>
      <div align="center" id="flash" class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

<%= render "partials/sidenav" %>
<%= render "partials/topnav" %>

<%= yield %>

  <%= render "partials/footer" %>
  <%= javascript_include_tag 'footermanifest', 'data-turbolinks-track' => true %>

</body>
</html>

<% else %>
<!DOCTYPE html>
<html>
<head>
  <title>GentelellaOnRails</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <style>
    /*Devise flash*/
    .alert-error {
      background-color: #f2dede;
      border-color: #eed3d7;
      color: #b94a48;
      text-align: center;
    }
    .alert-alert {
      background-color: #f2dede;
      border-color: #eed3d7;
      color: #b94a48;
      text-align: center;
    }
    .alert-notice {
      background-color: #dff0d8;
      border-color: #d6e9c6;
      color: #468847;
      text-align: left;
    }
  </style>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>

<body style="background:#F7F7F7;">

<div class="container body">

  <% flash.each do |key, value| %>
      <div align="center" id="flash" class="alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul style="text-align: center">
          <l>
          <b> <%= value %>  </b>
          </l>
        </ul>
      </div>
  <% end %>
  <div class="containers">
    <%= yield %>
  </div>

</body>
<% end %>

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentellela Alela!</span></a>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "img.jpg", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Welcome,</span>
          <h2>John Doe</h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section">
         
          <ul class="nav side-menu">

            <li><a href=<%= ranches_path %>><i class="fa fa-home"></i> Home </a>

            </li>
            <li><a href=<%= staffs_path %>><i class="fa fa-users"></i> Staff <span class="fa fa-chevron-down"></span></a>

            <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="general_elements.html">General Elements</a>
                </li>
                <li><a href="media_gallery.html">Media Gallery</a>
                </li>
                <li><a href="typography.html">Typography</a>
                </li>
                <li><a href="icons.html">Icons</a>
                </li>
                <li><a href="glyphicons.html">Glyphicons</a>
                </li>
                <li><a href="widgets.html">Widgets</a>
                </li>
                <li><a href="invoice.html">Invoice</a>
                </li>
                <li><a href="inbox.html">Inbox</a>
                </li>
                <li><a href="calendar.html">Calendar</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="tables.html">Tables</a>
                </li>
                <li><a href="tables_dynamic.html">Table Dynamic</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="chartjs.html">Chart JS</a>
                </li>
                <li><a href="chartjs2.html">Chart JS2</a>
                </li>
                <li><a href="morisjs.html">Moris JS</a>
                </li>
                <li><a href="echarts.html">ECharts </a>
                </li>
                <li><a href="other_charts.html">Other Charts </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="menu_section">
          <h3>Live On</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="e_commerce.html">E-commerce</a>
                </li>
                <li><a href="projects.html">Projects</a>
                </li>
                <li><a href="project_detail.html">Project Detail</a>
                </li>
                <li><a href="contacts.html">Contacts</a>
                </li>
                <li><a href="profile.html">Profile</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="page_404.html">404 Error</a>
                </li>
                <li><a href="page_500.html">500 Error</a>
                </li>
                <li><a href="plain_page.html">Plain Page</a>
                </li>
                <li><a href="login.html">Login Page</a>
                </li>
                <li><a href="pricing_tables.html">Pricing Tables</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="#level1_1">Level One</a>
                <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="display: none">
                    <li class="sub_menu"><a href="level2.html">Level Two</a>
                    </li>
                    <li><a href="#level2_1">Level Two</a>
                    </li>
                    <li><a href="#level2_2">Level Two</a>
                    </li>
                  </ul>
                </li>
                <li><a href="#level1_2">Level One</a>
                </li>
              </ul>
            </li>
            <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a>
            </li>
          </ul>
        </div>

      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
          <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/ranches/_form.html.erb
<%= form_for(@ranch) do |f| %>
  <% if @ranch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranch.errors.count, "error") %> prohibited this ranch from being saved:</h2>

      <ul>
      <% @ranch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>



  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ranches/edit.html.erb
<h1>Editing Ranch</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranch %> |
<%= link_to 'Back', ranches_path %>

app/views/ranches/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">

    <div class="row" style="width: auto; height: 100%;">
      <div class="col-md-12 col-sm-12 col-xs-12" >
        <div class="x_panel" style="text-align: center; height: auto; width: 50%; border-radius: 5px">
          
          <h1>Your Ranches</h1>

          <% @ranches.each do |ranch| %>
            <div class="index_row clearfix">
              <h2>
                <%= link_to ranch.name, ranch %>
              </h2>
            </div>
          <% end %>
          <%= link_to 'New Ranch', new_ranch_path, class: "btn btn-success", style: "margin: 10px;"  %>
          </div>

         
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/ranches/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">

      <div class="title_left">
        <h3>Plain Page</h3>
      </div>
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:700px; border-radius: 10px">
          <div class="x_title">
            <h2>Today </h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <h1>New Ranch</h1>

            <%= render 'form' %>

          <%= link_to 'Back', ranches_path %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/ranches/show.html.erb
<!-- page content -->
<div class="right_col" role="main">
  
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:700px; border-radius: 10px">
          <div class="x_title">
            <div id="tasks_wrapper">
             <div id="form">
              <%= render "tasks/form" %>
            </div>
          </div>
            <div class="clearfix"></div>
          </div>

          <h2>Today </h2>
          

          <div id="tasks_wrapper">
            <%= render "tasks/show"%>
          </div>

          <%= link_to 'Edit', edit_ranch_path(@ranch) %> 
          <%= link_to 'Back', ranches_path %>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <%= fields_for(@staff_ranch) do |x| %>
    <div class="field">
  
      <%= x.collection_select(:ranch_id, @all_ranch, :id, :name, { }, {:multiple => true}) %>
    </div>
  <%end%>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<div class="right_col" role="main">
  
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">


<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>



      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/staffs/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">

    <div class="row" style="width: auto; height: 100%;">
      <div class="col-md-12 col-sm-12 col-xs-12" >
        <div class="x_panel" style="text-align: center; height: auto; width: 50%; border-radius: 5px">
          
          <h1>Your Staffs</h1>

          <% @staffs.each do |staff| %>
            <div class="index_row clearfix">
              <h2>
                <%= link_to staff.name, staff %>
              </h2>
            </div>
          <% end %>
          <%= link_to 'New Staff', new_staff_path, class: "btn btn-success", style: "margin: 10px;"  %>
          </div>

         
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/staffs/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">

      <div class="title_left">
        <h3>Plain Page</h3>
      </div>
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:700px; border-radius: 10px">
          <div class="x_title">
            <h2>Today </h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <h1>New Staff</h1>

            <%= render 'form' %>

          <%= link_to 'Back', staffs_path %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/staffs/show.html.erb
<!-- page content -->
<div class="right_col" role="main">
  
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        
        <h1><%=@staff.name%></h1>
        
          <%= link_to 'Edit', edit_staff_path(@staff) %> 
          <%= link_to 'Back', staffs_path %>

      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/tasks/_form.html.erb
<div class="row-clearfix">
<%= form_for([@ranch, @ranch.tasks.build]) do |f| %>

  <%= f.text_field :content, placeholder: "New task", style: "width: 600px; border: solid 0.1px" %>

  <%= f.text_field :date, 'data-behaviour' => 'datepicker',style: "width: 100px; border: solid 0.1px"  %>

  <script type="text/javascript">
  $('[data-behaviour~=datepicker]').datepicker({
    autoclose: true
  });
</script>

  <%= f.submit%>
<% end %>
</div>

app/views/tasks/_show.html.erb
 <div id="show_task_table">


    <table>
          <% @tasks.each do |task| %>
          <div>
          </div>
            <%- if task.done == false %>
              <tr class="bubble_task">

                <td>
                  <div class="tbox">
                    <%= link_to done_ranch_task_path(@ranch, task.id), method: :patch do %>
                      <i class="fa fa-square-o" style="font-size:20px;"></i>
                    <% end %>
                  </div>
                </td>

                <td>
                  <div class="tline">
                    <p style="font-size: 20px"><%=task.content%></p>
                  </div>
                </td>

                <td>
                  <%- if task.star == false %>
                    <div class="star">
                      <%= link_to star_ranch_task_path(@ranch, task.id), method: :patch do %>
                      <i class="fa fa-star-o" style="font-size:20px;"></i>
                    <% end %>
                    </div>
                  <%else%>
                    <div class="star">
                      <%= link_to unstar_ranch_task_path(@ranch, task.id), method: :patch do %>
                      <i class="fa fa-star" style="font-size:20px;"></i>
                    <% end %>
                    </div>
                  <%end%>
                </td>


              </tr>
            <%else%>
              <tr class="bubble_task">

                <td>
                  <div class="tbox">
                    <%= link_to undone_ranch_task_path(@ranch, task.id), method: :patch do %>
                      <i class="fa fa-check-square-o" style="font-size:20px; opacity: 0.6;"></i>
                    <% end %>
                  </div>
                </td>

                <td>
                  <div class="tline">
                    <p style="opacity: 0.6; font-size: 20px"><%=task.content%></p>
                  </div>
                </td>

                   <td>
                  <%- if task.star == false %>
                    <div class="star">
                      <%= link_to star_ranch_task_path(@ranch, task.id), method: :patch do %>
                      <i class="fa fa-star-o" style="font-size:20px; opacity: 0.6;"></i>
                    <% end %>
                    </div>
                  <%else%>
                    <div class="star">
                      <%= link_to unstar_ranch_task_path(@ranch, task.id), method: :patch do %>
                      <i class="fa fa-star" style="font-size:20px; opacity: 0.6;"></i>
                    <% end %>
                    </div>
                  <%end%>
                

                <td>
                  <div class="trash">
                    <%= link_to ranch_task_path(@ranch, task.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="fa fa-times" style="font-size:20px; opacity: 0.6;"></i>
                    <% end %>
                  </div>
                </td>

              </tr>
            <%end%>
          <%end%>    
        </tbody>
      </table>

app/views/tasks/_tasks.html.erb
<p>
  <%= task.content %>
</p>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.user %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>